# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f58468821129cca2f63923a2d8debdae"
name = "Bundle-product-discount-test-2"
handle = "bundle-product-discount-test-2"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, write_discounts, read_discounts, write_discounts_allocator_functions, read_products"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[pos]
embedded = false
